name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    # set up android platform toosl
    - uses: malinskiy/action-android/install-sdk@release/0.1
    - run: sdkmanager platform-tools
    - run: echo $ANDROID_HOME

    - name: Build packages
      run: ./gradlew --no-daemon clean build
